/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docs: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  docs: [
    /*{
      type: "autogenerated",
      dirName: "introduction",
    },
    {
      type: "autogenerated",
      dirName: "whitepaper",
    },
    /*{
      type: "category",
      label: "Whitepaper",
      items: ["whitepaper"],
    },*/
    /*{
      type: "autogenerated",
      dirName: "faq",
    },
    {
      type: "autogenerated",
      dirName: "testnet",
    },
    {
      type: "autogenerated",
      dirName: "developers",
    },*/
    {
      type: 'category',
      label: 'Overview',
      collapsed: false, // collapsed by default
      items: [
        'Overview/about',
        'Overview/dates',
        'Overview/participate',
        'Overview/points',
        'Overview/support',
      ],
    },
    {
      type: 'category',
      label: 'Rules',
      collapsed: false, // expanded by default
      items: [
        'Rules/submissions',
        'Rules/referrals',
        'Rules/rewards',
        'Rules/disputes',
      ],
    },
  ],
};

export default sidebars;